INSERT INTO CUSTOMER(NAME,COUNTRY_ID, CUSTOMER_VALUE) VALUES ('Walter White',22,5);
INSERT INTO CUSTOMER(NAME,COUNTRY_ID, CUSTOMER_VALUE) VALUES ('Jon Snow',33, 3);
INSERT INTO CUSTOMER(NAME,COUNTRY_ID, CUSTOMER_VALUE) VALUES ('Elliot Alderson',44, 2);
INSERT INTO CUSTOMER(NAME,COUNTRY_ID, CUSTOMER_VALUE) VALUES ('Takeshi Kovac',55, 4);
INSERT INTO CUSTOMER(NAME,COUNTRY_ID, CUSTOMER_VALUE) VALUES ('Frank Underwood',66, 5);
INSERT INTO CUSTOMER(NAME,COUNTRY_ID, CUSTOMER_VALUE) VALUES ('Jesse Custer',122, 3);