spring:
  h2.console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:h2:file:~/customer
    username: sa
    password:
    driver-class-name: org.h2.Driver
    data: classpath:sql/init.sql
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: create-drop